spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: easywash
    password: easywash
server:
  port: 8282
mybatis:
  mapper-locations: classpath:mapper/*.xml